Add Call to Action for finalising user profile
freestyle-players-association/fpa-app pull request #35
Opened 2024-09-08 19:32 UTC by fdnklg

2024-09-08 20:14 UTC, zzZCodeZzz approved these changes
finds gut, hab mir nur die frage gestellt ob wir den cta button in der layout datei haben wollen, damit der in der nav immer sichtbar sind.

gerne mergen wenn du es so lassen willst

2024-09-08 20:54 UTC, zzZCodeZzz requested changes

2024-09-08 20:54 UTC, zzZCodeZzz commented on hooks/useIsProfileFinalised.ts
> +export function useIsProfileFinalised(profile: Tables<"userprofiles"> | null) {
lieber nicht in hook form, wenn wir das in server components nutzen

2024-09-19 08:41 UTC, fdnklg commented on hooks/useIsProfileFinalised.ts
> +export function useIsProfileFinalised(profile: Tables<"userprofiles"> | null) {
Created a server side version of the `getUserProfileInfoFinalised` function. This way we can ensure that sensitive user data is never exposed to the client. Also checking complete user information on the server makes sure that both client and server stay in sync.

2024-09-19 08:47 UTC, zzZCodeZzz approved these changes

2024-09-19 08:48 UTC, merged